version: '2'
services:
  service-lapps-converter:
    scale: 2 
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 30000
      strategy: recreate
      reinitializing_timeout: 60000